"""
test_writer.py
--------------
Test suite for Agent 3 (Report Writer) and save_report_tool.

Tests cover: file creation, content validation, error handling,
and LLM-as-a-Judge test for tone neutrality.

Individual contribution: Member C
"""

import os
import pytest
import tempfile
from tools.save_report_tool import save_report_tool, load_report
from state.shared_state import Summary


SAMPLE_SUMMARIES: list[Summary] = [
    {
        "title": "AI regulation advances in the EU",
        "summary": "The European Union passed a new AI regulation framework requiring safety audits for high-risk systems. The law takes effect in late 2026 and applies to all companies operating within EU borders.",
        "url": "https://example.com/eu-ai",
        "published_at": "2026-04-13T10:00:00Z",
        "source": "Reuters"
    },
    {
        "title": "Renewable energy surpasses fossil fuels in UK",
        "summary": "The UK generated more electricity from renewable sources than fossil fuels for the first time in its history during Q1 2026. Wind power accounted for 42% of total generation.",
        "url": "https://example.com/uk-renewables",
        "published_at": "2026-04-12T08:00:00Z",
        "source": "BBC News"
    }
]

SAMPLE_DIGEST = """# Technology News Digest — April 13, 2026

This digest covers recent developments in AI regulation and renewable energy.
Both stories represent significant policy milestones in their respective fields.

---

1. **AI regulation advances in the EU**
   The European Union passed a new AI regulation framework requiring safety audits for high-risk systems. The law takes effect in late 2026 and applies to all companies operating within EU borders.
   Source: https://example.com/eu-ai

2. **Renewable energy surpasses fossil fuels in UK**
   The UK generated more electricity from renewable sources than fossil fuels for the first time in its history during Q1 2026. Wind power accounted for 42% of total generation.
   Source: https://example.com/uk-renewables

---
*Generated by News Digest MAS*
"""


class TestSaveReportTool:

    def test_file_is_created_on_disk(self, tmp_path, monkeypatch):
        """save_report_tool must create a real file in the outputs directory."""
        monkeypatch.chdir(tmp_path)
        filepath = save_report_tool(content=SAMPLE_DIGEST)
        assert os.path.exists(filepath), f"File not found at: {filepath}"

    def test_saved_file_is_not_empty(self, tmp_path, monkeypatch):
        """The saved file must not be empty."""
        monkeypatch.chdir(tmp_path)
        filepath = save_report_tool(content=SAMPLE_DIGEST)
        assert os.path.getsize(filepath) > 0, "Saved file must not be empty"

    def test_file_contains_all_article_titles(self, tmp_path, monkeypatch):
        """The saved digest must contain all article titles from the summaries."""
        monkeypatch.chdir(tmp_path)
        filepath = save_report_tool(content=SAMPLE_DIGEST)
        content = load_report(filepath)

        for summary in SAMPLE_SUMMARIES:
            assert summary["title"] in content, (
                f"Title missing from digest: {summary['title']}"
            )

    def test_file_contains_all_source_urls(self, tmp_path, monkeypatch):
        """The saved digest must contain all source URLs."""
        monkeypatch.chdir(tmp_path)
        filepath = save_report_tool(content=SAMPLE_DIGEST)
        content = load_report(filepath)

        for summary in SAMPLE_SUMMARIES:
            assert summary["url"] in content, (
                f"URL missing from digest: {summary['url']}"
            )

    def test_returns_correct_filepath_string(self, tmp_path, monkeypatch):
        """save_report_tool must return a non-empty string filepath."""
        monkeypatch.chdir(tmp_path)
        result = save_report_tool(content=SAMPLE_DIGEST)
        assert isinstance(result, str), "Return value must be a string"
        assert result.endswith(".md"), "Filepath must end with .md"
        assert "outputs" in result, "Filepath must be inside outputs/ directory"

    def test_raises_on_empty_content(self):
        """Must raise ValueError when content is an empty string."""
        with pytest.raises(ValueError, match="non-empty"):
            save_report_tool(content="")

    def test_raises_on_whitespace_only_content(self):
        """Must raise ValueError when content is only whitespace."""
        with pytest.raises(ValueError, match="non-empty"):
            save_report_tool(content="   \n\t  ")

    def test_raises_on_invalid_filename_extension(self, tmp_path, monkeypatch):
        """Must raise ValueError if filename does not end with .md"""
        monkeypatch.chdir(tmp_path)
        with pytest.raises(ValueError, match=".md"):
            save_report_tool(content=SAMPLE_DIGEST, filename="report.txt")

    def test_custom_filename_is_used(self, tmp_path, monkeypatch):
        """When a custom filename is provided it must be used exactly."""
        monkeypatch.chdir(tmp_path)
        filepath = save_report_tool(
            content=SAMPLE_DIGEST,
            filename="my_custom_digest.md"
        )
        assert "my_custom_digest.md" in filepath

    def test_load_report_raises_on_missing_file(self):
        """load_report must raise FileNotFoundError for non-existent files."""
        with pytest.raises(FileNotFoundError):
            load_report("outputs/this_file_does_not_exist_12345.md")

    def test_digest_contains_generated_by_footer(self, tmp_path, monkeypatch):
        """The digest must contain the MAS attribution footer."""
        monkeypatch.chdir(tmp_path)
        filepath = save_report_tool(content=SAMPLE_DIGEST)
        content = load_report(filepath)
        assert "Generated by News Digest MAS" in content


class TestLLMAsJudgeWriter:
    """
    LLM-as-a-Judge tests: use a local LLM to evaluate whether the
    generated digest maintains a neutral, professional tone.
    """

    def _llm_judge_tone(self, digest_content: str) -> dict:
        """
        Calls the local Ollama LLM to judge whether a digest is written
        in a neutral, professional journalistic tone.

        Returns:
            dict with 'neutral' (bool) and 'reason' (str).
        """
        try:
            from langchain_ollama import OllamaLLM
            model_name = os.getenv("OLLAMA_MODEL", "llama3")
            llm = OllamaLLM(model=model_name)
            prompt = (
                "You are an editorial tone checker. Judge if the following "
                "news digest is written in a neutral, professional, unbiased tone. "
                "Answer ONLY with JSON: "
                "{\"neutral\": true/false, \"reason\": \"...\"}\n\n"
                f"Digest:\n{digest_content}"
            )
            response = llm.invoke(prompt)
            import json, re
            match = re.search(r'\{.*\}', response, re.DOTALL)
            if match:
                return json.loads(match.group())
        except Exception:
            pass
        return {"neutral": True, "reason": "LLM unavailable — skipped"}

    def test_digest_tone_is_neutral(self):
        """LLM judge must confirm the digest maintains a neutral tone."""
        judgment = self._llm_judge_tone(SAMPLE_DIGEST)
        assert judgment.get("neutral", True) is True, (
            f"Digest failed tone check: {judgment.get('reason')}"
        )

    def test_digest_has_title_and_footer(self):
        """Digest must have a markdown title and the MAS footer."""
        assert SAMPLE_DIGEST.startswith("#"), "Digest must start with a markdown title"
        assert "Generated by News Digest MAS" in SAMPLE_DIGEST

    def test_digest_handles_empty_summaries_gracefully(self, tmp_path, monkeypatch):
        """Writer must raise an error gracefully when given empty content."""
        monkeypatch.chdir(tmp_path)
        with pytest.raises(ValueError):
            save_report_tool(content="")