"""
Agent 2 — Summarizer for the News Summarizer MAS.

Responsible for filtering raw articles using filter_articles_tool,
then using the local LLM (via Ollama) to summarize each article into
2-3 clear, factual sentences. Writes cleaned summaries to shared state.

Individual contribution: Member B
"""

import os
from crewai import Agent, Task, Crew
from crewai.tools import tool
from state.shared_state import NewsState, Article, Summary
from tools.filter_tool import filter_articles_tool
from logger.agent_logger import log_agent_run
from llm_config import get_crewai_llm, crewai_tool_calls_enabled


SUMMARIZER_SYSTEM_PROMPT = """
You are a precise and factual news summarizer. Your job is to read
news article content and distill it into a concise, accurate summary.

Your responsibilities:
- Summarize each article in exactly 2-3 sentences
- Capture the most important facts: who, what, when, where
- Preserve the original meaning without distortion
- Write in a neutral, journalistic tone

Strict constraints:
- NEVER add information not present in the article text
- NEVER speculate, infer, or hallucinate facts
- NEVER express personal opinions or bias
- If an article is unclear or too short, write: "Article content insufficient for summary."
- Do not combine information from multiple articles into one summary
"""


@tool("filter_articles_tool")
def crewai_filter_tool(articles_json: str) -> str:
    """
    Filters a JSON array of raw articles to remove low-quality entries
    before summarization. Removes duplicates, placeholder content, and
    articles that are too short.

    Args:
        articles_json: A JSON string of article dicts from the Fetcher agent.

    Returns:
        A JSON string of filtered article dicts ready for summarization.
    """
    import json
    articles: list[Article] = json.loads(articles_json)
    filtered = filter_articles_tool(articles=articles, min_content_length=150)
    return json.dumps(filtered, ensure_ascii=False)

def build_summarizer_agent() -> Agent:
    """
    Builds and returns the configured CrewAI Summarizer agent.

    Returns:
        Agent: A CrewAI Agent with the Summarizer persona, system prompt,
               and filter_articles_tool attached.
    """
    return Agent(
        role="News Summarizer",
        goal=(
            "Filter raw articles for quality, then summarize each one into "
            "2-3 factual sentences using only the information provided."
        ),
        backstory=SUMMARIZER_SYSTEM_PROMPT.strip(),
        llm=get_crewai_llm(),
        tools=[crewai_filter_tool],
        verbose=True,
        allow_delegation=False,
        max_iter=5
    )

def build_summarizer_task(agent: Agent, articles: list[Article]) -> Task:
    """
    Builds the CrewAI Task for the Summarizer agent.

    Args:
        agent (Agent): The Summarizer agent instance.
        articles (list[Article]): Raw articles from the Fetcher agent.

    Returns:
        Task: A configured CrewAI Task for the Summarizer agent.
    """
    import json
    articles_json = json.dumps(articles, ensure_ascii=False)

    return Task(
        description=(
            f"You have received {len(articles)} raw articles as JSON:\n\n"
            f"{articles_json[:2000]}...\n\n"
            "Step 1: Use the filter_articles_tool to remove low-quality articles.\n"
            "Step 2: For each remaining article, write a 2-3 sentence summary "
            "using ONLY the information in the article content.\n"
            "Step 3: Return the results as a JSON array."
        ),
        expected_output=(
            "A JSON array of summary objects. Each object must contain: "
            "title (str), summary (str, 2-3 sentences), url (str), "
            "published_at (str), source (str)."
        ),
        agent=agent
    )

def _build_summaries_directly(articles: list[Article]) -> list[Summary]:
    """
    Fallback: builds summaries by calling the LLM directly via Ollama
    if CrewAI output parsing fails.

    Args:
        articles (list[Article]): Filtered articles to summarize.

    Returns:
        list[Summary]: Summaries generated by the local LLM.
    """
    from langchain_ollama import OllamaLLM

    model_name = os.getenv("OLLAMA_MODEL", "llama3")
    llm = OllamaLLM(model=model_name)
    filtered = filter_articles_tool(articles=articles, min_content_length=150)
    summaries: list[Summary] = []

    for article in filtered:
        prompt = (
            f"Summarize this news article in exactly 2-3 sentences. "
            f"Use only information from the article. Do not add anything extra.\n\n"
            f"Title: {article['title']}\n"
            f"Content: {article['content']}\n\n"
            f"Summary:"
        )
        try:
            summary_text: str = llm.invoke(prompt).strip()
        except Exception:
            summary_text = "Article content insufficient for summary."

        summaries.append(Summary(
            title=article["title"],
            summary=summary_text,
            url=article["url"],
            published_at=article["published_at"],
            source=article["source"]
        ))

    return summaries

def run_summarizer_agent(state: NewsState) -> NewsState:
    """
    Runs the Summarizer agent on raw_articles from state, populates
    state['summaries'], and logs the run.

    Args:
        state (NewsState): Current shared state with 'raw_articles' populated.

    Returns:
        NewsState: Updated state with 'summaries' populated.

    Raises:
        RuntimeError: If no articles remain after filtering.
    """
    import json

    raw_articles: list[Article] = state["raw_articles"]

    agent = build_summarizer_agent()
    task = build_summarizer_task(agent, raw_articles)

    result = None
    if crewai_tool_calls_enabled():
        try:
            crew = Crew(agents=[agent], tasks=[task], verbose=True)
            result = crew.kickoff()
        except Exception:
            result = None

    summaries: list[Summary] = []
    try:
        raw_text: str = str(result)
        start = raw_text.find("[")
        end = raw_text.rfind("]") + 1
        json_str = raw_text[start:end]
        summaries = json.loads(json_str)
    except (ValueError, json.JSONDecodeError):
        summaries = _build_summaries_directly(raw_articles)

    state["summaries"] = summaries

    log_agent_run(
        state=state,
        agent_name="Summarizer",
        input_data={"article_count": len(raw_articles)},
        tool_called="filter_articles_tool",
        tool_output=f"{len(summaries)} articles after filtering",
        output_data=[s["title"] for s in summaries],
        status="success" if summaries else "error"
    )

    if not summaries:
        raise RuntimeError(
            "Summarizer agent produced 0 summaries. "
            "All articles may have been filtered out."
        )

    print(f"[Summarizer] Produced {len(summaries)} summaries.")
    return state