"""
Agent 3 — Report Writer for the News Summarizer MAS.

Responsible for taking cleaned summaries from the shared state,
using the LLM to format them into a polished markdown news digest,
then saving the digest to disk using save_report_tool.

Individual contribution: Member C
"""

import os
from crewai import Agent, Task, Crew
from crewai.tools import tool
from datetime import datetime, timezone
from state.shared_state import NewsState, Summary
from tools.save_report_tool import save_report_tool
from logger.agent_logger import log_agent_run
from llm_config import get_crewai_llm, crewai_tool_calls_enabled


WRITER_SYSTEM_PROMPT = """
You are a professional news editor producing a clean, well-structured
daily news digest for a general audience.

Your responsibilities:
- Take a list of article summaries and format them into a polished digest
- Write in clear, neutral, journalistic prose
- Produce a markdown-formatted document with a title, intro, article
  sections, and a closing line

Strict constraints:
- Do NOT add any facts, figures, or claims not present in the summaries
- Do NOT express personal opinions or editorial bias
- Do NOT skip any articles from the summaries provided
- Maintain a professional, neutral tone throughout
- Each article section must include: a numbered heading, the summary
  text, and the source URL on a new line
"""


@tool("save_report_tool")
def crewai_save_report_tool(content: str) -> str:
    """
    Saves the formatted news digest markdown content to a local file
    in the outputs/ directory. Generates a timestamped filename automatically.

    Args:
        content: The complete formatted digest markdown string to save.

    Returns:
        The full relative file path of the saved digest file.
    """
    filepath = save_report_tool(content=content)
    return filepath

def build_writer_agent() -> Agent:
    """
    Builds and returns the configured CrewAI Report Writer agent.

    Returns:
        Agent: A CrewAI Agent with the Writer persona, system prompt,
               and save_report_tool attached.
    """
    return Agent(
        role="News Digest Writer",
        goal=(
            "Format article summaries into a polished, professional markdown "
            "news digest and save it to disk using the save_report_tool."
        ),
        backstory=WRITER_SYSTEM_PROMPT.strip(),
        llm=get_crewai_llm(),
        tools=[crewai_save_report_tool],
        verbose=True,
        allow_delegation=False,
        max_iter=3
    )

def build_writer_task(
    agent: Agent,
    summaries: list[Summary],
    topic: str
) -> Task:
    """
    Builds the CrewAI Task for the Report Writer agent.

    Args:
        agent (Agent): The Writer agent instance.
        summaries (list[Summary]): Cleaned summaries from the Summarizer agent.
        topic (str): The original user topic for the digest title.

    Returns:
        Task: A configured CrewAI Task for the Writer agent.
    """
    import json
    summaries_json = json.dumps(summaries, ensure_ascii=False)
    today = datetime.now(timezone.utc).strftime("%B %d, %Y")

    return Task(
        description=(
            f"You have {len(summaries)} article summaries on the topic: '{topic}'.\n\n"
            f"Summaries:\n{summaries_json}\n\n"
            f"Format them into a markdown news digest with:\n"
            f"1. A title: '# {topic.title()} News Digest — {today}'\n"
            f"2. A 2-3 sentence intro paragraph\n"
            f"3. Each article as a numbered section with its summary and URL\n"
            f"4. A closing line: '*Generated by News Digest MAS*'\n\n"
            f"Then use the save_report_tool to save the complete digest."
        ),
        expected_output=(
            "Confirmation that the digest was saved successfully, including "
            "the file path returned by save_report_tool."
        ),
        agent=agent
    )

def _build_digest_directly(
    summaries: list[Summary],
    topic: str
) -> str:
    """
    Fallback: generates the digest markdown using the LLM directly
    via Ollama if CrewAI task output is unparseable.

    Args:
        summaries (list[Summary]): Cleaned summaries to format.
        topic (str): The news topic for the digest title.

    Returns:
        str: A formatted markdown digest string.
    """
    today = datetime.now(timezone.utc).strftime("%B %d, %Y")

    title = f"# {topic.title()} News Digest — {today}"
    intro = (
        f"This digest summarizes {len(summaries)} recent articles related to {topic}. "
        "Each item below condenses the key points from the available article text."
    )

    sections: list[str] = []
    for i, summary in enumerate(summaries, 1):
        article_title = (summary.get("title") or "(Untitled)").strip()
        article_summary = (summary.get("summary") or "").strip() or "Article content insufficient for summary."
        url = (summary.get("url") or "").strip()

        sections.append(
            f"## {i}. {article_title}\n\n"
            f"{article_summary}\n\n"
            f"Source: {url}".rstrip()
        )

    body = "\n\n".join(sections)

    return (
        f"{title}\n\n"
        f"{intro}\n\n"
        f"{body}\n\n"
        f"*Generated by News Digest MAS*"
    ).strip()

def run_writer_agent(state: NewsState) -> NewsState:
    """
    Runs the Report Writer agent, formats the digest, saves it to disk,
    populates state['report_path'], and logs the run.

    Args:
        state (NewsState): Current shared state with 'summaries' populated.

    Returns:
        NewsState: Updated state with 'report_path' set.

    Raises:
        RuntimeError: If the digest cannot be saved.
    """
    summaries: list[Summary] = state["summaries"]
    topic: str = state["topic"]

    agent = build_writer_agent()
    task = build_writer_task(agent, summaries, topic)

    result = None
    if crewai_tool_calls_enabled():
        try:
            crew = Crew(agents=[agent], tasks=[task], verbose=True)
            result = crew.kickoff()
        except Exception:
            result = None

    result_text: str = str(result)
    filepath: str = ""

    if "outputs" in result_text:
        import re
        match = re.search(r"outputs[\\/][\w\-\.]+\.md", result_text)
        if match:
            filepath = match.group(0)

    if not filepath:
        digest_content = _build_digest_directly(summaries, topic)
        filepath = save_report_tool(content=digest_content)

    state["report_path"] = filepath

    log_agent_run(
        state=state,
        agent_name="ReportWriter",
        input_data={"summary_count": len(summaries), "topic": topic},
        tool_called="save_report_tool",
        tool_output=f"File saved at {filepath}",
        output_data=filepath,
        status="success" if filepath else "error"
    )

    if not filepath:
        raise RuntimeError("Report Writer failed to save the digest file.")

    print(f"[Writer] Digest saved to: {filepath}")
    return state